id_joint:
  1  : r_shoulder_roll
  2  : r_shoulder_pitch
  3  : l_shoulder_roll
  4  : l_shoulder_pitch
  5  : r_hip_pitch
  6  : r_hip_roll
  7  : l_hip_pitch
  8  : l_hip_roll 
  9  : r_ankle_roll
  10 : r_ankle_pitch
  11 : l_ankle_roll
  12 : l_ankle_pitch 
module_list: [none, arm_control_module, action_module, walking_module]
module_button:
  1 : none
  2 : arm_control_module
  3 : action_module
  4 : walking_module

