# time parameter

mov_time : 3.0		# movement time

# target pose [deg]

tar_pose :
  r_hip_pitch   : 0.0
  r_hip_roll    : 0.0
  r_ankle_roll  : 0.0
  r_ankle_pitch : 0.0

  l_hip_pitch   : 0.0
  l_hip_roll    : 0.0
  l_ankle_roll  : 0.0
  l_ankle_pitch : 0.0

