# 1.0 -> 1 [deg]

r_hip_roll_gain  : 0.0
r_hip_pitch_gain : 0.0
r_ankle_pitch_gain : 0.0
r_ankle_roll_gain  : 0.0

l_hip_roll_gain  : 0.0
l_hip_pitch_gain : 0.0
l_knee_gain      : 0.0
l_ankle_pitch_gain : 0.0
l_ankle_roll_gain  : 0.0
