r_shoulder_pitch :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   shutdown                 : 56
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 600
   position_i_gain          : 150
   position_d_gain          : 50
      
r_shoulder_roll :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   shutdown                 : 56
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 150
   position_d_gain          : 50

l_shoulder_pitch :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   shutdown                 : 56
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 00
   position_i_gain          : 150
   position_d_gain          : 50
   
l_shoulder_roll :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   shutdown                 : 56
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 150
   position_d_gain          : 50
   
r_hip_roll :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   shutdown                 : 56
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
      
r_hip_pitch :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 150
   position_d_gain          : 50

l_hip_roll :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   shutdown                 : 56
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
l_hip_pitch :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 150
   position_d_gain          : 50
   
r_ankle_pitch  :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   
r_ankle_roll :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095

l_ankle_pitch :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   
l_ankle_roll:  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
