r_sho_pitch :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   shutdown                 : 56
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 600
   position_i_gain          : 150
   position_d_gain          : 50
      
r_sho_roll :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   shutdown                 : 56
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 150
   position_d_gain          : 50

l_sho_pitch :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   shutdown                 : 56
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 600
   position_i_gain          : 150
   position_d_gain          : 50
   
l_sho_roll :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   shutdown                 : 56
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 150
   position_d_gain          : 50
   
r_el_yaw :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   shutdown                 : 56
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
      
r_el_pitch :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 150
   position_d_gain          : 50

l_el_yaw :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   shutdown                 : 56
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
l_el_pitch :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 150
   position_d_gain          : 50
   
head_pan  :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   
head_tilt :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095

waist_pan :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   
waist_tilt:  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
