x_offset: 0
y_offset: 0
z_offset: 0
roll_offset: 0
pitch_offset: 0
yaw_offset: 0
hip_pitch_offset: 0
period_time: 2000
dsp_ratio: 0.3
step_forward_back_ratio: 0.28
foot_height: 0.04
swing_right_left: 0
swing_top_down: 0
pelvis_offset: 0
arm_swing_gain: 0
balance_hip_roll_gain: 0
balance_knee_gain: 0
balance_ankle_roll_gain: 0
balance_ankle_pitch_gain: 0
p_gain: 0
i_gain: 0
d_gain: 0